const book_order = {
  // This list converts the 10^6 of a rid to a book name.
  // Note: nulls are used to pad the array
  "index": [
    // Old Testament
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Songs",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    // New Testament
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",

    // Apocryphal (nulls should be removed when these are added)
    // "1 Esdras",
    // "Tobit",
    // "Judith",
    // "1 Maccabees",
    // "2 Maccabees",
    // "3 Maccabees",
    // "Prayer of Manasseh",
    // "Wisdom",
    // "Sirach",
    // "Psalms of Solomon",
    // "Baruch",
    // "Letter of Jeremiah",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    // Apostolic Fathers
    "Barnabas",
    "1 Clement",
    "2 Clement",
    "Didache",
    "Diognetus",
    null,
    "Ign. Eph.",
    "Ign. Magn.",
    "Ign. Phild.",
    "Ign. Pol.",
    "Ign. Rom.",
    "Ign. Smyrn.",
    "Ign. Trall.",
    "Mart. Pol.",
    "Pol. Phil.",
  ],
  "kjv": [
    // Old Testament
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Solomon",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    // Apocryphal
    "1 Esdras",
    "Tobit",
    "Judith",
    "1 Maccabees",
    "2 Maccabees",
    "3 Maccabees",
    "Prayer of Manasseh",
    "Wisdom",
    "Sirach",
    "Psalms of Solomon",
    "Baruch",
    "Letter of Jeremiah",
    // New Testament
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",
  ],
  "bhs": [
    // Old Testament
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "Isaiah",
    "Jeremiah",
    "Ezekiel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Psalms",
    "Proverbs",
    "Job",
    "Song of Solomon",
    "Ruth",
    "Lamentations",
    "Ecclesiastes",
    "Esther",
    "Daniel",
    "Ezra",
    "Nehemiah",
    "1 Chronicles",
    "2 Chronicles",
    // Apocryphal
    "1 Esdras",
    "Tobit",
    "Judith",
    "1 Maccabees",
    "2 Maccabees",
    "3 Maccabees",
    "Prayer of Manasseh",
    "Wisdom",
    "Sirach",
    "Psalms of Solomon",
    "Baruch",
    "Letter of Jeremiah",
    // New Testament
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",
  ],
  "lxx": [
    // Old Testament and Apocrypha
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "1 Esdras",
    "Ezra",
    "Nehemiah",
    "Tobit",
    "Judith",
    "Esther",
    "1 Maccabees",
    "2 Maccabees",
    "3 Maccabees",
    "Psalms",
    "Prayer of Manasseh",
    "Job",
    "Proverbs",
    "Ecclesiastes",
    "Song of Solomon",
    "Wisdom",
    "Sirach",
    "Psalms of Solomon",
    "Hosea",
    "Amos",
    "Micah",
    "Joel",
    "Obadiah",
    "Jonah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Isaiah",
    "Jeremiah",
    "Baruch",
    "Lamentations",
    "Letter of Jeremiah",
    "Ezekiel",
    "Daniel",
  ],
  "gnt": [
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",
  ],
};

const bookFromIndex = (index: number) => {
  return book_order["index"][index - 1];
};

export default (
  bookIdA: number,
  bookIdB: number,
  schema: VersificationSchema,
) => {
  const bookA = bookFromIndex(bookIdA);
  const bookB = bookFromIndex(bookIdB);
  if (!bookA || !bookB) {
    throw new Error(`Invalid book id: ${bookIdA} or ${bookIdB}`);
  }
  if (schema in book_order) {
    const schemaBookOrder = book_order[schema];
    const bookAIndex = schemaBookOrder.indexOf(bookA);
    const bookBIndex = schemaBookOrder.indexOf(bookB);
    if (bookAIndex !== -1 && bookBIndex !== -1) {
      return bookAIndex - bookBIndex;
    }
    return bookIdA - bookIdB;
  } else {
    return bookIdA - bookIdB;
  }
};
